# Generated by Django 3.1.7 on 2021-03-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cassandra_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Carx',
        ),
    ]
