# Generated by Django 3.1.7 on 2021-03-20 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(db_index=True, max_length=60, primary_key=True, serialize=False, verbose_name='id')),
                ('star_rating', models.IntegerField()),
                ('helpful_votes', models.IntegerField()),
                ('review_headline', models.CharField(max_length=500)),
                ('review_body', models.CharField(max_length=500)),
                ('review_date', models.DateField()),
                ('vine', models.CharField(max_length=1)),
                ('verified_purchase', models.CharField(max_length=1)),
                ('customer_id', models.IntegerField()),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
