# Generated by Django 3.1.7 on 2021-03-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210320_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='total_votes',
            field=models.IntegerField(null=True),
        ),
    ]
