# Generated by Django 3.1.7 on 2021-03-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_total_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_headline',
            field=models.CharField(max_length=1000),
        ),
    ]
