# Generated by Django 3.1.7 on 2021-03-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(db_index=True, max_length=60, primary_key=True, serialize=False, verbose_name='id')),
                ('product_parent', models.IntegerField()),
                ('product_title', models.CharField(max_length=500)),
                ('product_category', models.CharField(max_length=60)),
            ],
        ),
    ]
